# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: public/auth_tenant/v1/service.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'public/auth_tenant/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from public.auth_tenant.v1 import dto_pb2 as public_dot_auth__tenant_dot_v1_dot_dto__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#public/auth_tenant/v1/service.proto\x12\x0e\x61uth_tenant.v1\x1a\x1fpublic/auth_tenant/v1/dto.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xe2\x08\n\x17\x41uthTenantPublicService\x12|\n\x06WhoIAm\x12\x1d.auth_tenant.v1.WhoIAmRequest\x1a\x1e.auth_tenant.v1.WhoIAmResponse\"3\x92\x41\x12\x62\x10\n\x0e\n\nBearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/tenant/auth/whoiam\x12\x94\x01\n\x12\x41\x63\x63ountVerifyEmail\x12).auth_tenant.v1.AccountVerifyEmailRequest\x1a*.auth_tenant.v1.AccountVerifyEmailResponse\"\'\x82\xd3\xe4\x93\x02!\"\x1c/v1/tenant/auth/verify-email:\x01*\x12\x8c\x01\n\x10\x43heckAccountCode\x12\'.auth_tenant.v1.CheckAccountCodeRequest\x1a(.auth_tenant.v1.CheckAccountCodeResponse\"%\x82\xd3\xe4\x93\x02\x1f\"\x1a/v1/tenant/auth/check-code:\x01*\x12\x66\n\x05Login\x12\x1c.auth_tenant.v1.LoginRequest\x1a\x1d.auth_tenant.v1.LoginResponse\" \x82\xd3\xe4\x93\x02\x1a\"\x15/v1/tenant/auth/login:\x01*\x12\x7f\n\x06Logout\x12\x1d.auth_tenant.v1.LogoutRequest\x1a\x1e.auth_tenant.v1.LogoutResponse\"6\x92\x41\x12\x62\x10\n\x0e\n\nBearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1b\"\x16/v1/tenant/auth/logout:\x01*\x12n\n\x07Refresh\x12\x1e.auth_tenant.v1.RefreshRequest\x1a\x1f.auth_tenant.v1.RefreshResponse\"\"\x82\xd3\xe4\x93\x02\x1c\"\x17/v1/tenant/auth/refresh:\x01*\x12\xa8\x01\n\x17RequestPasswordRecovery\x12..auth_tenant.v1.RequestPasswordRecoveryRequest\x1a/.auth_tenant.v1.RequestPasswordRecoveryResponse\",\x82\xd3\xe4\x93\x02&\"!/v1/tenant/auth/password-recovery:\x01*\x12\x9e\x01\n\x14UpdatePasswordByCode\x12+.auth_tenant.v1.UpdatePasswordByCodeRequest\x1a,.auth_tenant.v1.UpdatePasswordByCodeResponse\"+\x82\xd3\xe4\x93\x02%\" /v1/tenant/auth/password-by-code:\x01*b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'public.auth_tenant.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHTENANTPUBLICSERVICE'].methods_by_name['WhoIAm']._loaded_options = None
  _globals['_AUTHTENANTPUBLICSERVICE'].methods_by_name['WhoIAm']._serialized_options = b'\222A\022b\020\n\016\n\nBearerAuth\022\000\202\323\344\223\002\030\022\026/v1/tenant/auth/whoiam'
  _globals['_AUTHTENANTPUBLICSERVICE'].methods_by_name['AccountVerifyEmail']._loaded_options = None
  _globals['_AUTHTENANTPUBLICSERVICE'].methods_by_name['AccountVerifyEmail']._serialized_options = b'\202\323\344\223\002!\"\034/v1/tenant/auth/verify-email:\001*'
  _globals['_AUTHTENANTPUBLICSERVICE'].methods_by_name['CheckAccountCode']._loaded_options = None
  _globals['_AUTHTENANTPUBLICSERVICE'].methods_by_name['CheckAccountCode']._serialized_options = b'\202\323\344\223\002\037\"\032/v1/tenant/auth/check-code:\001*'
  _globals['_AUTHTENANTPUBLICSERVICE'].methods_by_name['Login']._loaded_options = None
  _globals['_AUTHTENANTPUBLICSERVICE'].methods_by_name['Login']._serialized_options = b'\202\323\344\223\002\032\"\025/v1/tenant/auth/login:\001*'
  _globals['_AUTHTENANTPUBLICSERVICE'].methods_by_name['Logout']._loaded_options = None
  _globals['_AUTHTENANTPUBLICSERVICE'].methods_by_name['Logout']._serialized_options = b'\222A\022b\020\n\016\n\nBearerAuth\022\000\202\323\344\223\002\033\"\026/v1/tenant/auth/logout:\001*'
  _globals['_AUTHTENANTPUBLICSERVICE'].methods_by_name['Refresh']._loaded_options = None
  _globals['_AUTHTENANTPUBLICSERVICE'].methods_by_name['Refresh']._serialized_options = b'\202\323\344\223\002\034\"\027/v1/tenant/auth/refresh:\001*'
  _globals['_AUTHTENANTPUBLICSERVICE'].methods_by_name['RequestPasswordRecovery']._loaded_options = None
  _globals['_AUTHTENANTPUBLICSERVICE'].methods_by_name['RequestPasswordRecovery']._serialized_options = b'\202\323\344\223\002&\"!/v1/tenant/auth/password-recovery:\001*'
  _globals['_AUTHTENANTPUBLICSERVICE'].methods_by_name['UpdatePasswordByCode']._loaded_options = None
  _globals['_AUTHTENANTPUBLICSERVICE'].methods_by_name['UpdatePasswordByCode']._serialized_options = b'\202\323\344\223\002%\" /v1/tenant/auth/password-by-code:\001*'
  _globals['_AUTHTENANTPUBLICSERVICE']._serialized_start=167
  _globals['_AUTHTENANTPUBLICSERVICE']._serialized_end=1289
# @@protoc_insertion_point(module_scope)
