# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from public.auth_tenant.v1 import dto_pb2 as public_dot_auth__tenant_dot_v1_dot_dto__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in public/auth_tenant/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthTenantPublicServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WhoIAm = channel.unary_unary(
                '/auth_tenant.v1.AuthTenantPublicService/WhoIAm',
                request_serializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.WhoIAmRequest.SerializeToString,
                response_deserializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.WhoIAmResponse.FromString,
                _registered_method=True)
        self.AccountVerifyEmail = channel.unary_unary(
                '/auth_tenant.v1.AuthTenantPublicService/AccountVerifyEmail',
                request_serializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.AccountVerifyEmailRequest.SerializeToString,
                response_deserializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.AccountVerifyEmailResponse.FromString,
                _registered_method=True)
        self.CheckAccountCode = channel.unary_unary(
                '/auth_tenant.v1.AuthTenantPublicService/CheckAccountCode',
                request_serializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.CheckAccountCodeRequest.SerializeToString,
                response_deserializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.CheckAccountCodeResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/auth_tenant.v1.AuthTenantPublicService/Login',
                request_serializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.LoginRequest.SerializeToString,
                response_deserializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/auth_tenant.v1.AuthTenantPublicService/Logout',
                request_serializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.LogoutRequest.SerializeToString,
                response_deserializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.Refresh = channel.unary_unary(
                '/auth_tenant.v1.AuthTenantPublicService/Refresh',
                request_serializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.RefreshRequest.SerializeToString,
                response_deserializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.RefreshResponse.FromString,
                _registered_method=True)
        self.RequestPasswordRecovery = channel.unary_unary(
                '/auth_tenant.v1.AuthTenantPublicService/RequestPasswordRecovery',
                request_serializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.RequestPasswordRecoveryRequest.SerializeToString,
                response_deserializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.RequestPasswordRecoveryResponse.FromString,
                _registered_method=True)
        self.UpdatePasswordByCode = channel.unary_unary(
                '/auth_tenant.v1.AuthTenantPublicService/UpdatePasswordByCode',
                request_serializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.UpdatePasswordByCodeRequest.SerializeToString,
                response_deserializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.UpdatePasswordByCodeResponse.FromString,
                _registered_method=True)


class AuthTenantPublicServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WhoIAm(self, request, context):
        """WhoIAm
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccountVerifyEmail(self, request, context):
        """Верификация аккаунта по емаил
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAccountCode(self, request, context):
        """Проверить код аккаунта
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Login
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Logout
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refresh(self, request, context):
        """Refresh
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPasswordRecovery(self, request, context):
        """Запрос на восстановление пароля
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePasswordByCode(self, request, context):
        """Обновить пароль по коду
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthTenantPublicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WhoIAm': grpc.unary_unary_rpc_method_handler(
                    servicer.WhoIAm,
                    request_deserializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.WhoIAmRequest.FromString,
                    response_serializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.WhoIAmResponse.SerializeToString,
            ),
            'AccountVerifyEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.AccountVerifyEmail,
                    request_deserializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.AccountVerifyEmailRequest.FromString,
                    response_serializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.AccountVerifyEmailResponse.SerializeToString,
            ),
            'CheckAccountCode': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAccountCode,
                    request_deserializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.CheckAccountCodeRequest.FromString,
                    response_serializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.CheckAccountCodeResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.LoginRequest.FromString,
                    response_serializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.LogoutRequest.FromString,
                    response_serializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.LogoutResponse.SerializeToString,
            ),
            'Refresh': grpc.unary_unary_rpc_method_handler(
                    servicer.Refresh,
                    request_deserializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.RefreshRequest.FromString,
                    response_serializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.RefreshResponse.SerializeToString,
            ),
            'RequestPasswordRecovery': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPasswordRecovery,
                    request_deserializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.RequestPasswordRecoveryRequest.FromString,
                    response_serializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.RequestPasswordRecoveryResponse.SerializeToString,
            ),
            'UpdatePasswordByCode': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePasswordByCode,
                    request_deserializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.UpdatePasswordByCodeRequest.FromString,
                    response_serializer=public_dot_auth__tenant_dot_v1_dot_dto__pb2.UpdatePasswordByCodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth_tenant.v1.AuthTenantPublicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth_tenant.v1.AuthTenantPublicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthTenantPublicService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WhoIAm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_tenant.v1.AuthTenantPublicService/WhoIAm',
            public_dot_auth__tenant_dot_v1_dot_dto__pb2.WhoIAmRequest.SerializeToString,
            public_dot_auth__tenant_dot_v1_dot_dto__pb2.WhoIAmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccountVerifyEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_tenant.v1.AuthTenantPublicService/AccountVerifyEmail',
            public_dot_auth__tenant_dot_v1_dot_dto__pb2.AccountVerifyEmailRequest.SerializeToString,
            public_dot_auth__tenant_dot_v1_dot_dto__pb2.AccountVerifyEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAccountCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_tenant.v1.AuthTenantPublicService/CheckAccountCode',
            public_dot_auth__tenant_dot_v1_dot_dto__pb2.CheckAccountCodeRequest.SerializeToString,
            public_dot_auth__tenant_dot_v1_dot_dto__pb2.CheckAccountCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_tenant.v1.AuthTenantPublicService/Login',
            public_dot_auth__tenant_dot_v1_dot_dto__pb2.LoginRequest.SerializeToString,
            public_dot_auth__tenant_dot_v1_dot_dto__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_tenant.v1.AuthTenantPublicService/Logout',
            public_dot_auth__tenant_dot_v1_dot_dto__pb2.LogoutRequest.SerializeToString,
            public_dot_auth__tenant_dot_v1_dot_dto__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_tenant.v1.AuthTenantPublicService/Refresh',
            public_dot_auth__tenant_dot_v1_dot_dto__pb2.RefreshRequest.SerializeToString,
            public_dot_auth__tenant_dot_v1_dot_dto__pb2.RefreshResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestPasswordRecovery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_tenant.v1.AuthTenantPublicService/RequestPasswordRecovery',
            public_dot_auth__tenant_dot_v1_dot_dto__pb2.RequestPasswordRecoveryRequest.SerializeToString,
            public_dot_auth__tenant_dot_v1_dot_dto__pb2.RequestPasswordRecoveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePasswordByCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth_tenant.v1.AuthTenantPublicService/UpdatePasswordByCode',
            public_dot_auth__tenant_dot_v1_dot_dto__pb2.UpdatePasswordByCodeRequest.SerializeToString,
            public_dot_auth__tenant_dot_v1_dot_dto__pb2.UpdatePasswordByCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
