# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workers/ocr/ocr.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'workers/ocr/ocr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15workers/ocr/ocr.proto\x12\x06ocr.v1\"\x93\x01\n\tClientMsg\x12\x1e\n\x05start\x18\x01 \x01(\x0b\x32\r.ocr.v1.StartH\x00\x12!\n\x05\x63hunk\x18\x02 \x01(\x0b\x32\x10.ocr.v1.PdfChunkH\x00\x12\x1a\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x0b.ocr.v1.EndH\x00\x12\x1c\n\x04ping\x18\x04 \x01(\x0b\x32\x0c.ocr.v1.PingH\x00\x42\t\n\x07payload\"\xbc\x01\n\tServerMsg\x12\x1e\n\x05ready\x18\x01 \x01(\x0b\x32\r.ocr.v1.ReadyH\x00\x12\x1c\n\x04pong\x18\x02 \x01(\x0b\x32\x0c.ocr.v1.PongH\x00\x12$\n\x08progress\x18\x03 \x01(\x0b\x32\x10.ocr.v1.ProgressH\x00\x12 \n\x06result\x18\x04 \x01(\x0b\x32\x0e.ocr.v1.ResultH\x00\x12\x1e\n\x05\x65rror\x18\x05 \x01(\x0b\x32\r.ocr.v1.ErrorH\x00\x42\t\n\x07payload\"`\n\x05Start\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\x12\x0b\n\x03\x64pi\x18\x04 \x01(\x05\x12\x0e\n\x06\x64\x65vice\x18\x05 \x01(\t\"\x18\n\x08PdfChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x05\n\x03\x45nd\"!\n\x04Ping\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05ts_ms\x18\x02 \x01(\x03\"8\n\x05Ready\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0b\n\x03gpu\x18\x02 \x01(\x08\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t\"!\n\x04Pong\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05ts_ms\x18\x02 \x01(\x03\"-\n\x08Progress\x12\r\n\x05stage\x18\x01 \x01(\t\x12\x12\n\npages_done\x18\x02 \x01(\x05\"\xac\x01\n\x06Result\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06\x65ngine\x18\x02 \x01(\t\x12\x0b\n\x03gpu\x18\x03 \x01(\x08\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\x12\x0b\n\x03\x64pi\x18\x05 \x01(\x05\x12\x11\n\tlanguages\x18\x06 \x03(\t\x12\x12\n\npages_text\x18\x07 \x03(\t\x12\x10\n\x08\x66ilename\x18\x08 \x01(\t\x12\x1b\n\x13process_duration_ms\x18\t \x01(\x03\"\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\nOcrService\x12;\n\x0f\x45xtractTextBidi\x12\x11.ocr.v1.ClientMsg\x1a\x11.ocr.v1.ServerMsg(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workers.ocr.ocr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTMSG']._serialized_start=34
  _globals['_CLIENTMSG']._serialized_end=181
  _globals['_SERVERMSG']._serialized_start=184
  _globals['_SERVERMSG']._serialized_end=372
  _globals['_START']._serialized_start=374
  _globals['_START']._serialized_end=470
  _globals['_PDFCHUNK']._serialized_start=472
  _globals['_PDFCHUNK']._serialized_end=496
  _globals['_END']._serialized_start=498
  _globals['_END']._serialized_end=503
  _globals['_PING']._serialized_start=505
  _globals['_PING']._serialized_end=538
  _globals['_READY']._serialized_start=540
  _globals['_READY']._serialized_end=596
  _globals['_PONG']._serialized_start=598
  _globals['_PONG']._serialized_end=631
  _globals['_PROGRESS']._serialized_start=633
  _globals['_PROGRESS']._serialized_end=678
  _globals['_RESULT']._serialized_start=681
  _globals['_RESULT']._serialized_end=853
  _globals['_ERROR']._serialized_start=855
  _globals['_ERROR']._serialized_end=879
  _globals['_OCRSERVICE']._serialized_start=881
  _globals['_OCRSERVICE']._serialized_end=954
# @@protoc_insertion_point(module_scope)
