# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from public.testing.v1 import dto_pb2 as public_dot_testing_dot_v1_dot_dto__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in public/testing/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TestingPublicServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPersonalityTraits = channel.unary_unary(
                '/testing.v1.TestingPublicService/GetPersonalityTraits',
                request_serializer=public_dot_testing_dot_v1_dot_dto__pb2.GetPersonalityTraitsRequest.SerializeToString,
                response_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.GetPersonalityTraitsResponse.FromString,
                _registered_method=True)
        self.ListProfiles = channel.unary_unary(
                '/testing.v1.TestingPublicService/ListProfiles',
                request_serializer=public_dot_testing_dot_v1_dot_dto__pb2.ListProfilesRequest.SerializeToString,
                response_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.ListProfilesResponse.FromString,
                _registered_method=True)
        self.GetProfile = channel.unary_unary(
                '/testing.v1.TestingPublicService/GetProfile',
                request_serializer=public_dot_testing_dot_v1_dot_dto__pb2.GetProfileRequest.SerializeToString,
                response_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.GetProfileResponse.FromString,
                _registered_method=True)
        self.CreateProfile = channel.unary_unary(
                '/testing.v1.TestingPublicService/CreateProfile',
                request_serializer=public_dot_testing_dot_v1_dot_dto__pb2.CreateProfileRequest.SerializeToString,
                response_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.CreateProfileResponse.FromString,
                _registered_method=True)
        self.PatchProfile = channel.unary_unary(
                '/testing.v1.TestingPublicService/PatchProfile',
                request_serializer=public_dot_testing_dot_v1_dot_dto__pb2.PatchProfileRequest.SerializeToString,
                response_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.PatchProfileResponse.FromString,
                _registered_method=True)
        self.DeleteProfile = channel.unary_unary(
                '/testing.v1.TestingPublicService/DeleteProfile',
                request_serializer=public_dot_testing_dot_v1_dot_dto__pb2.DeleteProfileRequest.SerializeToString,
                response_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.DeleteProfileResponse.FromString,
                _registered_method=True)
        self.GenerateProfileDescriptionByName = channel.unary_unary(
                '/testing.v1.TestingPublicService/GenerateProfileDescriptionByName',
                request_serializer=public_dot_testing_dot_v1_dot_dto__pb2.GenerateProfileDescriptionByNameRequest.SerializeToString,
                response_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.GenerateProfileDescriptionByNameResponse.FromString,
                _registered_method=True)
        self.GenerateProfileTraitsMapByDescription = channel.unary_unary(
                '/testing.v1.TestingPublicService/GenerateProfileTraitsMapByDescription',
                request_serializer=public_dot_testing_dot_v1_dot_dto__pb2.GenerateProfileTraitsMapByDescriptionRequest.SerializeToString,
                response_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.GenerateProfileTraitsMapByDescriptionResponse.FromString,
                _registered_method=True)
        self.ListRooms = channel.unary_unary(
                '/testing.v1.TestingPublicService/ListRooms',
                request_serializer=public_dot_testing_dot_v1_dot_dto__pb2.ListRoomsRequest.SerializeToString,
                response_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.ListRoomsResponse.FromString,
                _registered_method=True)
        self.GetRoom = channel.unary_unary(
                '/testing.v1.TestingPublicService/GetRoom',
                request_serializer=public_dot_testing_dot_v1_dot_dto__pb2.GetRoomRequest.SerializeToString,
                response_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.GetRoomResponse.FromString,
                _registered_method=True)
        self.CreateRoom = channel.unary_unary(
                '/testing.v1.TestingPublicService/CreateRoom',
                request_serializer=public_dot_testing_dot_v1_dot_dto__pb2.CreateRoomRequest.SerializeToString,
                response_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.CreateRoomResponse.FromString,
                _registered_method=True)
        self.DeleteRoom = channel.unary_unary(
                '/testing.v1.TestingPublicService/DeleteRoom',
                request_serializer=public_dot_testing_dot_v1_dot_dto__pb2.DeleteRoomRequest.SerializeToString,
                response_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.DeleteRoomResponse.FromString,
                _registered_method=True)
        self.ProcessRoom = channel.unary_unary(
                '/testing.v1.TestingPublicService/ProcessRoom',
                request_serializer=public_dot_testing_dot_v1_dot_dto__pb2.ProcessRoomRequest.SerializeToString,
                response_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.ProcessRoomResponse.FromString,
                _registered_method=True)


class TestingPublicServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPersonalityTraits(self, request, context):
        """Получить список метрик
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProfiles(self, request, context):
        """Список профилей профессий
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfile(self, request, context):
        """Получить профиль профессии
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProfile(self, request, context):
        """Создать профиль профессии
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PatchProfile(self, request, context):
        """Обновить профиль профессии
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProfile(self, request, context):
        """Удалить профиль профессии
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateProfileDescriptionByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateProfileTraitsMapByDescription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRooms(self, request, context):
        """Список комнат
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoom(self, request, context):
        """Получить комнату
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRoom(self, request, context):
        """Создать комнату
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRoom(self, request, context):
        """Удалить комнату
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessRoom(self, request, context):
        """Обработать результаты комнаты
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestingPublicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPersonalityTraits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPersonalityTraits,
                    request_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.GetPersonalityTraitsRequest.FromString,
                    response_serializer=public_dot_testing_dot_v1_dot_dto__pb2.GetPersonalityTraitsResponse.SerializeToString,
            ),
            'ListProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProfiles,
                    request_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.ListProfilesRequest.FromString,
                    response_serializer=public_dot_testing_dot_v1_dot_dto__pb2.ListProfilesResponse.SerializeToString,
            ),
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.GetProfileRequest.FromString,
                    response_serializer=public_dot_testing_dot_v1_dot_dto__pb2.GetProfileResponse.SerializeToString,
            ),
            'CreateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProfile,
                    request_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.CreateProfileRequest.FromString,
                    response_serializer=public_dot_testing_dot_v1_dot_dto__pb2.CreateProfileResponse.SerializeToString,
            ),
            'PatchProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.PatchProfile,
                    request_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.PatchProfileRequest.FromString,
                    response_serializer=public_dot_testing_dot_v1_dot_dto__pb2.PatchProfileResponse.SerializeToString,
            ),
            'DeleteProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProfile,
                    request_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.DeleteProfileRequest.FromString,
                    response_serializer=public_dot_testing_dot_v1_dot_dto__pb2.DeleteProfileResponse.SerializeToString,
            ),
            'GenerateProfileDescriptionByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateProfileDescriptionByName,
                    request_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.GenerateProfileDescriptionByNameRequest.FromString,
                    response_serializer=public_dot_testing_dot_v1_dot_dto__pb2.GenerateProfileDescriptionByNameResponse.SerializeToString,
            ),
            'GenerateProfileTraitsMapByDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateProfileTraitsMapByDescription,
                    request_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.GenerateProfileTraitsMapByDescriptionRequest.FromString,
                    response_serializer=public_dot_testing_dot_v1_dot_dto__pb2.GenerateProfileTraitsMapByDescriptionResponse.SerializeToString,
            ),
            'ListRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRooms,
                    request_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.ListRoomsRequest.FromString,
                    response_serializer=public_dot_testing_dot_v1_dot_dto__pb2.ListRoomsResponse.SerializeToString,
            ),
            'GetRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoom,
                    request_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.GetRoomRequest.FromString,
                    response_serializer=public_dot_testing_dot_v1_dot_dto__pb2.GetRoomResponse.SerializeToString,
            ),
            'CreateRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRoom,
                    request_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.CreateRoomRequest.FromString,
                    response_serializer=public_dot_testing_dot_v1_dot_dto__pb2.CreateRoomResponse.SerializeToString,
            ),
            'DeleteRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRoom,
                    request_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.DeleteRoomRequest.FromString,
                    response_serializer=public_dot_testing_dot_v1_dot_dto__pb2.DeleteRoomResponse.SerializeToString,
            ),
            'ProcessRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessRoom,
                    request_deserializer=public_dot_testing_dot_v1_dot_dto__pb2.ProcessRoomRequest.FromString,
                    response_serializer=public_dot_testing_dot_v1_dot_dto__pb2.ProcessRoomResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'testing.v1.TestingPublicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('testing.v1.TestingPublicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TestingPublicService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPersonalityTraits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testing.v1.TestingPublicService/GetPersonalityTraits',
            public_dot_testing_dot_v1_dot_dto__pb2.GetPersonalityTraitsRequest.SerializeToString,
            public_dot_testing_dot_v1_dot_dto__pb2.GetPersonalityTraitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testing.v1.TestingPublicService/ListProfiles',
            public_dot_testing_dot_v1_dot_dto__pb2.ListProfilesRequest.SerializeToString,
            public_dot_testing_dot_v1_dot_dto__pb2.ListProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testing.v1.TestingPublicService/GetProfile',
            public_dot_testing_dot_v1_dot_dto__pb2.GetProfileRequest.SerializeToString,
            public_dot_testing_dot_v1_dot_dto__pb2.GetProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testing.v1.TestingPublicService/CreateProfile',
            public_dot_testing_dot_v1_dot_dto__pb2.CreateProfileRequest.SerializeToString,
            public_dot_testing_dot_v1_dot_dto__pb2.CreateProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PatchProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testing.v1.TestingPublicService/PatchProfile',
            public_dot_testing_dot_v1_dot_dto__pb2.PatchProfileRequest.SerializeToString,
            public_dot_testing_dot_v1_dot_dto__pb2.PatchProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testing.v1.TestingPublicService/DeleteProfile',
            public_dot_testing_dot_v1_dot_dto__pb2.DeleteProfileRequest.SerializeToString,
            public_dot_testing_dot_v1_dot_dto__pb2.DeleteProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateProfileDescriptionByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testing.v1.TestingPublicService/GenerateProfileDescriptionByName',
            public_dot_testing_dot_v1_dot_dto__pb2.GenerateProfileDescriptionByNameRequest.SerializeToString,
            public_dot_testing_dot_v1_dot_dto__pb2.GenerateProfileDescriptionByNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateProfileTraitsMapByDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testing.v1.TestingPublicService/GenerateProfileTraitsMapByDescription',
            public_dot_testing_dot_v1_dot_dto__pb2.GenerateProfileTraitsMapByDescriptionRequest.SerializeToString,
            public_dot_testing_dot_v1_dot_dto__pb2.GenerateProfileTraitsMapByDescriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testing.v1.TestingPublicService/ListRooms',
            public_dot_testing_dot_v1_dot_dto__pb2.ListRoomsRequest.SerializeToString,
            public_dot_testing_dot_v1_dot_dto__pb2.ListRoomsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testing.v1.TestingPublicService/GetRoom',
            public_dot_testing_dot_v1_dot_dto__pb2.GetRoomRequest.SerializeToString,
            public_dot_testing_dot_v1_dot_dto__pb2.GetRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testing.v1.TestingPublicService/CreateRoom',
            public_dot_testing_dot_v1_dot_dto__pb2.CreateRoomRequest.SerializeToString,
            public_dot_testing_dot_v1_dot_dto__pb2.CreateRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testing.v1.TestingPublicService/DeleteRoom',
            public_dot_testing_dot_v1_dot_dto__pb2.DeleteRoomRequest.SerializeToString,
            public_dot_testing_dot_v1_dot_dto__pb2.DeleteRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testing.v1.TestingPublicService/ProcessRoom',
            public_dot_testing_dot_v1_dot_dto__pb2.ProcessRoomRequest.SerializeToString,
            public_dot_testing_dot_v1_dot_dto__pb2.ProcessRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
