# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: public/rooms/v1/dto.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'public/rooms/v1/dto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.types import types_pb2 as common_dot_types_dot_types__pb2
from common.types import testing_types_pb2 as common_dot_types_dot_testing__types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19public/rooms/v1/dto.proto\x12\x08rooms.v1\x1a\x18\x63ommon/types/types.proto\x1a common/types/testing_types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1b\x62uf/validate/validate.proto\x1a\x19google/protobuf/any.proto\"\'\n\rRoomCandidate\x12\x16\n\x0e\x63\x61ndidate_name\x18\x01 \x01(\t\"b\n\x11RoomTechniqueItem\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.types.v1.TechniqueItemType\x12\x10\n\x08question\x18\x02 \x01(\t\x12\x10\n\x08variants\x18\x03 \x03(\t\"\xae\x01\n\x04Room\x12\n\n\x02id\x18\x01 \x01(\t\x12$\n\x06status\x18\x02 \x01(\x0e\x32\x14.types.v1.RoomStatus\x12\x13\n\x0btenant_name\x18\x03 \x01(\t\x12*\n\tcandidate\x18\x04 \x01(\x0b\x32\x17.rooms.v1.RoomCandidate\x12\x33\n\x0etechnique_data\x18\x05 \x03(\x0b\x32\x1b.rooms.v1.RoomTechniqueItem\"q\n\x0b\x41nswerValue\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x12\x13\n\tint_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x42\x07\n\x05value\"x\n\x07\x41nswers\x12)\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1b.rooms.v1.Answers.DataEntry\x1a\x42\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.rooms.v1.AnswerValue:\x02\x38\x01\"\x1c\n\x0eGetRoomRequest\x12\n\n\x02id\x18\x01 \x01(\t\"/\n\x0fGetRoomResponse\x12\x1c\n\x04room\x18\x01 \x01(\x0b\x32\x0e.rooms.v1.Room\">\n\x18\x46inishRoomRequestPayload\x12\"\n\x07\x61nswers\x18\x01 \x01(\x0b\x32\x11.rooms.v1.Answers\"f\n\x11\x46inishRoomRequest\x12\x14\n\x02id\x18\x01 \x01(\tB\x08\xbaH\x05r\x03\xb0\x01\x01\x12;\n\x07payload\x18\x02 \x01(\x0b\x32\".rooms.v1.FinishRoomRequestPayloadB\x06\xbaH\x03\xc8\x01\x01\"\x14\n\x12\x46inishRoomResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'public.rooms.v1.dto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANSWERS_DATAENTRY']._loaded_options = None
  _globals['_ANSWERS_DATAENTRY']._serialized_options = b'8\001'
  _globals['_FINISHROOMREQUEST'].fields_by_name['id']._loaded_options = None
  _globals['_FINISHROOMREQUEST'].fields_by_name['id']._serialized_options = b'\272H\005r\003\260\001\001'
  _globals['_FINISHROOMREQUEST'].fields_by_name['payload']._loaded_options = None
  _globals['_FINISHROOMREQUEST'].fields_by_name['payload']._serialized_options = b'\272H\003\310\001\001'
  _globals['_ROOMCANDIDATE']._serialized_start=188
  _globals['_ROOMCANDIDATE']._serialized_end=227
  _globals['_ROOMTECHNIQUEITEM']._serialized_start=229
  _globals['_ROOMTECHNIQUEITEM']._serialized_end=327
  _globals['_ROOM']._serialized_start=330
  _globals['_ROOM']._serialized_end=504
  _globals['_ANSWERVALUE']._serialized_start=506
  _globals['_ANSWERVALUE']._serialized_end=619
  _globals['_ANSWERS']._serialized_start=621
  _globals['_ANSWERS']._serialized_end=741
  _globals['_ANSWERS_DATAENTRY']._serialized_start=675
  _globals['_ANSWERS_DATAENTRY']._serialized_end=741
  _globals['_GETROOMREQUEST']._serialized_start=743
  _globals['_GETROOMREQUEST']._serialized_end=771
  _globals['_GETROOMRESPONSE']._serialized_start=773
  _globals['_GETROOMRESPONSE']._serialized_end=820
  _globals['_FINISHROOMREQUESTPAYLOAD']._serialized_start=822
  _globals['_FINISHROOMREQUESTPAYLOAD']._serialized_end=884
  _globals['_FINISHROOMREQUEST']._serialized_start=886
  _globals['_FINISHROOMREQUEST']._serialized_end=988
  _globals['_FINISHROOMRESPONSE']._serialized_start=990
  _globals['_FINISHROOMRESPONSE']._serialized_end=1010
# @@protoc_insertion_point(module_scope)
