# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: public/rooms/v1/service.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'public/rooms/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from public.rooms.v1 import dto_pb2 as public_dot_rooms_dot_v1_dot_dto__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dpublic/rooms/v1/service.proto\x12\x08rooms.v1\x1a\x19public/rooms/v1/dto.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xd7\x01\n\x12RoomsPublicService\x12V\n\x07GetRoom\x12\x18.rooms.v1.GetRoomRequest\x1a\x19.rooms.v1.GetRoomResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/rooms/{id}\x12i\n\nFinishRoom\x12\x1b.rooms.v1.FinishRoomRequest\x1a\x1c.rooms.v1.FinishRoomResponse\" \x82\xd3\xe4\x93\x02\x1a\"\x15/v1/rooms/{id}/finish:\x01*b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'public.rooms.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROOMSPUBLICSERVICE'].methods_by_name['GetRoom']._loaded_options = None
  _globals['_ROOMSPUBLICSERVICE'].methods_by_name['GetRoom']._serialized_options = b'\202\323\344\223\002\020\022\016/v1/rooms/{id}'
  _globals['_ROOMSPUBLICSERVICE'].methods_by_name['FinishRoom']._loaded_options = None
  _globals['_ROOMSPUBLICSERVICE'].methods_by_name['FinishRoom']._serialized_options = b'\202\323\344\223\002\032\"\025/v1/rooms/{id}/finish:\001*'
  _globals['_ROOMSPUBLICSERVICE']._serialized_start=149
  _globals['_ROOMSPUBLICSERVICE']._serialized_end=364
# @@protoc_insertion_point(module_scope)
