# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from public.rooms.v1 import dto_pb2 as public_dot_rooms_dot_v1_dot_dto__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in public/rooms/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoomsPublicServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRoom = channel.unary_unary(
                '/rooms.v1.RoomsPublicService/GetRoom',
                request_serializer=public_dot_rooms_dot_v1_dot_dto__pb2.GetRoomRequest.SerializeToString,
                response_deserializer=public_dot_rooms_dot_v1_dot_dto__pb2.GetRoomResponse.FromString,
                _registered_method=True)
        self.FinishRoom = channel.unary_unary(
                '/rooms.v1.RoomsPublicService/FinishRoom',
                request_serializer=public_dot_rooms_dot_v1_dot_dto__pb2.FinishRoomRequest.SerializeToString,
                response_deserializer=public_dot_rooms_dot_v1_dot_dto__pb2.FinishRoomResponse.FromString,
                _registered_method=True)


class RoomsPublicServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRoom(self, request, context):
        """Получить комнату
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishRoom(self, request, context):
        """Завершить комнату
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoomsPublicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoom,
                    request_deserializer=public_dot_rooms_dot_v1_dot_dto__pb2.GetRoomRequest.FromString,
                    response_serializer=public_dot_rooms_dot_v1_dot_dto__pb2.GetRoomResponse.SerializeToString,
            ),
            'FinishRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishRoom,
                    request_deserializer=public_dot_rooms_dot_v1_dot_dto__pb2.FinishRoomRequest.FromString,
                    response_serializer=public_dot_rooms_dot_v1_dot_dto__pb2.FinishRoomResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rooms.v1.RoomsPublicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rooms.v1.RoomsPublicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoomsPublicService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rooms.v1.RoomsPublicService/GetRoom',
            public_dot_rooms_dot_v1_dot_dto__pb2.GetRoomRequest.SerializeToString,
            public_dot_rooms_dot_v1_dot_dto__pb2.GetRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinishRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rooms.v1.RoomsPublicService/FinishRoom',
            public_dot_rooms_dot_v1_dot_dto__pb2.FinishRoomRequest.SerializeToString,
            public_dot_rooms_dot_v1_dot_dto__pb2.FinishRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
