# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/workflows/workflows.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'common/workflows/workflows.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n common/workflows/workflows.proto\x12\x0cworkflows.v1\"\xd3\x02\n\x1eWorkflowProcessResumeFileInput\x12\x11\n\tresume_id\x18\x01 \x01(\t\x12\x43\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x35.workflows.v1.WorkflowProcessResumeFileInput.FileData\x1a\x8a\x01\n\x08\x46ileData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0estorage_bucket\x18\x02 \x01(\t\x12\x13\n\x0bstorage_key\x18\x03 \x01(\t\x12\x43\n\x04type\x18\x04 \x01(\x0e\x32\x35.workflows.v1.WorkflowProcessResumeFileInput.FileType\"L\n\x08\x46ileType\x12\x19\n\x15\x46ILE_TYPE_UNSPECIFIED\x10\x00\x12\x11\n\rFILE_TYPE_PDF\x10\x01\x12\x12\n\x0e\x46ILE_TYPE_WORD\x10\x02\"1\n\x1fWorkflowProcessResumeFileOutput\x12\x0e\n\x06status\x18\x01 \x01(\t*F\n\x0eWorkflowsQueue\x12\x1b\n\x17WORKFLOWS_QUEUE_DEFAULT\x10\x00\x12\x17\n\x13WORKFLOWS_QUEUE_OCR\x10\x01*F\n\x08Workflow\x12\x18\n\x14WORKFLOW_UNSPECIFIED\x10\x00\x12 \n\x1cWORKFLOW_PROCESS_RESUME_FILE\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.workflows.workflows_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKFLOWSQUEUE']._serialized_start=443
  _globals['_WORKFLOWSQUEUE']._serialized_end=513
  _globals['_WORKFLOW']._serialized_start=515
  _globals['_WORKFLOW']._serialized_end=585
  _globals['_WORKFLOWPROCESSRESUMEFILEINPUT']._serialized_start=51
  _globals['_WORKFLOWPROCESSRESUMEFILEINPUT']._serialized_end=390
  _globals['_WORKFLOWPROCESSRESUMEFILEINPUT_FILEDATA']._serialized_start=174
  _globals['_WORKFLOWPROCESSRESUMEFILEINPUT_FILEDATA']._serialized_end=312
  _globals['_WORKFLOWPROCESSRESUMEFILEINPUT_FILETYPE']._serialized_start=314
  _globals['_WORKFLOWPROCESSRESUMEFILEINPUT_FILETYPE']._serialized_end=390
  _globals['_WORKFLOWPROCESSRESUMEFILEOUTPUT']._serialized_start=392
  _globals['_WORKFLOWPROCESSRESUMEFILEOUTPUT']._serialized_end=441
# @@protoc_insertion_point(module_scope)
