# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/types/crm_types.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'common/types/crm_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.types import types_pb2 as common_dot_types_dot_types__pb2
from google.type import date_pb2 as google_dot_type_dot_date__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63ommon/types/crm_types.proto\x12\x08types.v1\x1a\x18\x63ommon/types/types.proto\x1a\x16google/type/date.proto\"\xed\x01\n\tCandidate\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x03\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0f\n\x07surname\x18\x05 \x01(\t\x12 \n\x06gender\x18\x06 \x01(\x0e\x32\x10.types.v1.Gender\x12(\n\x08\x62irthday\x18\x07 \x01(\x0b\x32\x11.google.type.DateH\x00\x88\x01\x01\x12(\n\x0bresume_file\x18\x08 \x01(\x0b\x32\x0e.types.v1.FileH\x01\x88\x01\x01\x42\x0b\n\t_birthdayB\x0e\n\x0c_resume_file\"\xb7\x01\n\rListCandidate\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x03\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0f\n\x07surname\x18\x05 \x01(\t\x12 \n\x06gender\x18\x06 \x01(\x0e\x32\x10.types.v1.Gender\x12(\n\x08\x62irthday\x18\x07 \x01(\x0b\x32\x11.google.type.DateH\x00\x88\x01\x01\x42\x0b\n\t_birthdayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.types.crm_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CANDIDATE']._serialized_start=93
  _globals['_CANDIDATE']._serialized_end=330
  _globals['_LISTCANDIDATE']._serialized_start=333
  _globals['_LISTCANDIDATE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
