# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/types/types.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'common/types/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.type import date_pb2 as google_dot_type_dot_date__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63ommon/types/types.proto\x12\x08types.v1\x1a\x16google/type/date.proto\"O\n\x04\x46ile\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0f\n\x02id\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08\x66ilename\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x05\n\x03_idB\x0b\n\t_filename\"p\n\x08\x46ilesMap\x12(\n\x03map\x18\x01 \x03(\x0b\x32\x1b.types.v1.FilesMap.MapEntry\x1a:\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.types.v1.File:\x02\x38\x01\"=\n\x0cOptionalDate\x12$\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x11.google.type.DateH\x00\x88\x01\x01\x42\x07\n\x05_date*D\n\x06Gender\x12\x16\n\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n\x0bGENDER_MALE\x10\x01\x12\x11\n\rGENDER_FEMALE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.types.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILESMAP_MAPENTRY']._loaded_options = None
  _globals['_FILESMAP_MAPENTRY']._serialized_options = b'8\001'
  _globals['_GENDER']._serialized_start=320
  _globals['_GENDER']._serialized_end=388
  _globals['_FILE']._serialized_start=62
  _globals['_FILE']._serialized_end=141
  _globals['_FILESMAP']._serialized_start=143
  _globals['_FILESMAP']._serialized_end=255
  _globals['_FILESMAP_MAPENTRY']._serialized_start=197
  _globals['_FILESMAP_MAPENTRY']._serialized_end=255
  _globals['_OPTIONALDATE']._serialized_start=257
  _globals['_OPTIONALDATE']._serialized_end=318
# @@protoc_insertion_point(module_scope)
