# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/types/users_tenant_types.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'common/types/users_tenant_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.types import types_pb2 as common_dot_types_dot_types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%common/types/users_tenant_types.proto\x12\x08types.v1\x1a\x18\x63ommon/types/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x04\n\rAccountTenant\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x03\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x12\x0f\n\x07role_id\x18\x04 \x01(\x04\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x14\n\x0cis_confirmed\x18\x06 \x01(\x08\x12\x19\n\x11is_email_verified\x18\x07 \x01(\x08\x12\x12\n\nis_blocked\x18\x08 \x01(\x08\x12\x14\n\x0cprofile_name\x18\t \x01(\t\x12\x17\n\x0fprofile_surname\x18\n \x01(\t\x12?\n\x0eprofile_photos\x18\x0b \x01(\x0b\x32\".types.v1.AccountTenant.PhotoFilesH\x00\x88\x01\x01\x12\x36\n\rlast_login_at\x18\r \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01\x88\x01\x01\x12\x38\n\x0flast_request_at\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x02\x88\x01\x01\x1aZ\n\nPhotoFiles\x12%\n\roriginal_file\x18\x01 \x01(\x0b\x32\x0e.types.v1.File\x12%\n\rs100x100_file\x18\x02 \x01(\x0b\x32\x0e.types.v1.FileB\x11\n\x0f_profile_photosB\x10\n\x0e_last_login_atB\x12\n\x10_last_request_atb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.types.users_tenant_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTTENANT']._serialized_start=111
  _globals['_ACCOUNTTENANT']._serialized_end=650
  _globals['_ACCOUNTTENANT_PHOTOFILES']._serialized_start=503
  _globals['_ACCOUNTTENANT_PHOTOFILES']._serialized_end=593
# @@protoc_insertion_point(module_scope)
