# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from public.crm.v1 import dto_pb2 as public_dot_crm_dot_v1_dot_dto__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in public/crm/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CrmPublicServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCandidates = channel.unary_unary(
                '/crm.v1.CrmPublicService/ListCandidates',
                request_serializer=public_dot_crm_dot_v1_dot_dto__pb2.ListCandidatesRequest.SerializeToString,
                response_deserializer=public_dot_crm_dot_v1_dot_dto__pb2.ListCandidatesResponse.FromString,
                _registered_method=True)
        self.GetCandidate = channel.unary_unary(
                '/crm.v1.CrmPublicService/GetCandidate',
                request_serializer=public_dot_crm_dot_v1_dot_dto__pb2.GetCandidateRequest.SerializeToString,
                response_deserializer=public_dot_crm_dot_v1_dot_dto__pb2.GetCandidateResponse.FromString,
                _registered_method=True)
        self.CreateCandidate = channel.unary_unary(
                '/crm.v1.CrmPublicService/CreateCandidate',
                request_serializer=public_dot_crm_dot_v1_dot_dto__pb2.CreateCandidateRequest.SerializeToString,
                response_deserializer=public_dot_crm_dot_v1_dot_dto__pb2.CreateCandidateResponse.FromString,
                _registered_method=True)
        self.PatchCandidate = channel.unary_unary(
                '/crm.v1.CrmPublicService/PatchCandidate',
                request_serializer=public_dot_crm_dot_v1_dot_dto__pb2.PatchCandidateRequest.SerializeToString,
                response_deserializer=public_dot_crm_dot_v1_dot_dto__pb2.PatchCandidateResponse.FromString,
                _registered_method=True)
        self.DeleteCandidate = channel.unary_unary(
                '/crm.v1.CrmPublicService/DeleteCandidate',
                request_serializer=public_dot_crm_dot_v1_dot_dto__pb2.DeleteCandidateRequest.SerializeToString,
                response_deserializer=public_dot_crm_dot_v1_dot_dto__pb2.DeleteCandidateResponse.FromString,
                _registered_method=True)
        self.UploadCandidateResumeFile = channel.unary_unary(
                '/crm.v1.CrmPublicService/UploadCandidateResumeFile',
                request_serializer=public_dot_crm_dot_v1_dot_dto__pb2.UploadCandidateResumeFileRequest.SerializeToString,
                response_deserializer=public_dot_crm_dot_v1_dot_dto__pb2.UploadCandidateResumeFileResponse.FromString,
                _registered_method=True)


class CrmPublicServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListCandidates(self, request, context):
        """Список кандидатов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCandidate(self, request, context):
        """Получить кандидата
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCandidate(self, request, context):
        """Создать кандидата
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PatchCandidate(self, request, context):
        """Обновить кандидата
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCandidate(self, request, context):
        """Удалить кандидата
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadCandidateResumeFile(self, request, context):
        """Загрузить файл-резюме кандидата
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrmPublicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCandidates,
                    request_deserializer=public_dot_crm_dot_v1_dot_dto__pb2.ListCandidatesRequest.FromString,
                    response_serializer=public_dot_crm_dot_v1_dot_dto__pb2.ListCandidatesResponse.SerializeToString,
            ),
            'GetCandidate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCandidate,
                    request_deserializer=public_dot_crm_dot_v1_dot_dto__pb2.GetCandidateRequest.FromString,
                    response_serializer=public_dot_crm_dot_v1_dot_dto__pb2.GetCandidateResponse.SerializeToString,
            ),
            'CreateCandidate': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCandidate,
                    request_deserializer=public_dot_crm_dot_v1_dot_dto__pb2.CreateCandidateRequest.FromString,
                    response_serializer=public_dot_crm_dot_v1_dot_dto__pb2.CreateCandidateResponse.SerializeToString,
            ),
            'PatchCandidate': grpc.unary_unary_rpc_method_handler(
                    servicer.PatchCandidate,
                    request_deserializer=public_dot_crm_dot_v1_dot_dto__pb2.PatchCandidateRequest.FromString,
                    response_serializer=public_dot_crm_dot_v1_dot_dto__pb2.PatchCandidateResponse.SerializeToString,
            ),
            'DeleteCandidate': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCandidate,
                    request_deserializer=public_dot_crm_dot_v1_dot_dto__pb2.DeleteCandidateRequest.FromString,
                    response_serializer=public_dot_crm_dot_v1_dot_dto__pb2.DeleteCandidateResponse.SerializeToString,
            ),
            'UploadCandidateResumeFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadCandidateResumeFile,
                    request_deserializer=public_dot_crm_dot_v1_dot_dto__pb2.UploadCandidateResumeFileRequest.FromString,
                    response_serializer=public_dot_crm_dot_v1_dot_dto__pb2.UploadCandidateResumeFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crm.v1.CrmPublicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crm.v1.CrmPublicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CrmPublicService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crm.v1.CrmPublicService/ListCandidates',
            public_dot_crm_dot_v1_dot_dto__pb2.ListCandidatesRequest.SerializeToString,
            public_dot_crm_dot_v1_dot_dto__pb2.ListCandidatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCandidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crm.v1.CrmPublicService/GetCandidate',
            public_dot_crm_dot_v1_dot_dto__pb2.GetCandidateRequest.SerializeToString,
            public_dot_crm_dot_v1_dot_dto__pb2.GetCandidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCandidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crm.v1.CrmPublicService/CreateCandidate',
            public_dot_crm_dot_v1_dot_dto__pb2.CreateCandidateRequest.SerializeToString,
            public_dot_crm_dot_v1_dot_dto__pb2.CreateCandidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PatchCandidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crm.v1.CrmPublicService/PatchCandidate',
            public_dot_crm_dot_v1_dot_dto__pb2.PatchCandidateRequest.SerializeToString,
            public_dot_crm_dot_v1_dot_dto__pb2.PatchCandidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCandidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crm.v1.CrmPublicService/DeleteCandidate',
            public_dot_crm_dot_v1_dot_dto__pb2.DeleteCandidateRequest.SerializeToString,
            public_dot_crm_dot_v1_dot_dto__pb2.DeleteCandidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadCandidateResumeFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crm.v1.CrmPublicService/UploadCandidateResumeFile',
            public_dot_crm_dot_v1_dot_dto__pb2.UploadCandidateResumeFileRequest.SerializeToString,
            public_dot_crm_dot_v1_dot_dto__pb2.UploadCandidateResumeFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
