# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: public/crm/v1/service.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'public/crm/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from public.crm.v1 import dto_pb2 as public_dot_crm_dot_v1_dot_dto__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bpublic/crm/v1/service.proto\x12\x06\x63rm.v1\x1a\x17public/crm/v1/dto.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xf8\x06\n\x10\x43rmPublicService\x12\x80\x01\n\x0eListCandidates\x12\x1d.crm.v1.ListCandidatesRequest\x1a\x1e.crm.v1.ListCandidatesResponse\"/\x92\x41\x12\x62\x10\n\x0e\n\nBearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/crm/candidates\x12\x7f\n\x0cGetCandidate\x12\x1b.crm.v1.GetCandidateRequest\x1a\x1c.crm.v1.GetCandidateResponse\"4\x92\x41\x12\x62\x10\n\x0e\n\nBearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/crm/candidates/{id}\x12\x86\x01\n\x0f\x43reateCandidate\x12\x1e.crm.v1.CreateCandidateRequest\x1a\x1f.crm.v1.CreateCandidateResponse\"2\x92\x41\x12\x62\x10\n\x0e\n\nBearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x17\"\x12/v1/crm/candidates:\x01*\x12\x88\x01\n\x0ePatchCandidate\x12\x1d.crm.v1.PatchCandidateRequest\x1a\x1e.crm.v1.PatchCandidateResponse\"7\x92\x41\x12\x62\x10\n\x0e\n\nBearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1c\x32\x17/v1/crm/candidates/{id}:\x01*\x12\x88\x01\n\x0f\x44\x65leteCandidate\x12\x1e.crm.v1.DeleteCandidateRequest\x1a\x1f.crm.v1.DeleteCandidateResponse\"4\x92\x41\x12\x62\x10\n\x0e\n\nBearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x19*\x17/v1/crm/candidates/{id}\x12\xc0\x01\n\x19UploadCandidateResumeFile\x12(.crm.v1.UploadCandidateResumeFileRequest\x1a).crm.v1.UploadCandidateResumeFileResponse\"N\x92\x41\'2\x13multipart/form-datab\x10\n\x0e\n\nBearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1e\"\x19/v1/crm/candidates-resume:\x01*b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'public.crm.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CRMPUBLICSERVICE'].methods_by_name['ListCandidates']._loaded_options = None
  _globals['_CRMPUBLICSERVICE'].methods_by_name['ListCandidates']._serialized_options = b'\222A\022b\020\n\016\n\nBearerAuth\022\000\202\323\344\223\002\024\022\022/v1/crm/candidates'
  _globals['_CRMPUBLICSERVICE'].methods_by_name['GetCandidate']._loaded_options = None
  _globals['_CRMPUBLICSERVICE'].methods_by_name['GetCandidate']._serialized_options = b'\222A\022b\020\n\016\n\nBearerAuth\022\000\202\323\344\223\002\031\022\027/v1/crm/candidates/{id}'
  _globals['_CRMPUBLICSERVICE'].methods_by_name['CreateCandidate']._loaded_options = None
  _globals['_CRMPUBLICSERVICE'].methods_by_name['CreateCandidate']._serialized_options = b'\222A\022b\020\n\016\n\nBearerAuth\022\000\202\323\344\223\002\027\"\022/v1/crm/candidates:\001*'
  _globals['_CRMPUBLICSERVICE'].methods_by_name['PatchCandidate']._loaded_options = None
  _globals['_CRMPUBLICSERVICE'].methods_by_name['PatchCandidate']._serialized_options = b'\222A\022b\020\n\016\n\nBearerAuth\022\000\202\323\344\223\002\0342\027/v1/crm/candidates/{id}:\001*'
  _globals['_CRMPUBLICSERVICE'].methods_by_name['DeleteCandidate']._loaded_options = None
  _globals['_CRMPUBLICSERVICE'].methods_by_name['DeleteCandidate']._serialized_options = b'\222A\022b\020\n\016\n\nBearerAuth\022\000\202\323\344\223\002\031*\027/v1/crm/candidates/{id}'
  _globals['_CRMPUBLICSERVICE'].methods_by_name['UploadCandidateResumeFile']._loaded_options = None
  _globals['_CRMPUBLICSERVICE'].methods_by_name['UploadCandidateResumeFile']._serialized_options = b'\222A\'2\023multipart/form-datab\020\n\016\n\nBearerAuth\022\000\202\323\344\223\002\036\"\031/v1/crm/candidates-resume:\001*'
  _globals['_CRMPUBLICSERVICE']._serialized_start=143
  _globals['_CRMPUBLICSERVICE']._serialized_end=1031
# @@protoc_insertion_point(module_scope)
