# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: public/registration/v1/dto.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'public/registration/v1/dto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.types import types_pb2 as common_dot_types_dot_types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n public/registration/v1/dto.proto\x12\x0fregistration.v1\x1a\x18\x63ommon/types/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1b\x62uf/validate/validate.proto\")\n\x18StartRegistrationRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\x1b\n\x19StartRegistrationResponse\"\x8d\x01\n FinishRegistrationRequestPayload\x12\"\n\x0etenant_text_id\x18\x01 \x01(\tB\n\xbaH\x07r\x05\x10\x01\x18\x96\x01\x12 \n\x0cprofile_name\x18\x02 \x01(\tB\n\xbaH\x07r\x05\x10\x01\x18\x96\x01\x12#\n\x0fprofile_surname\x18\x03 \x01(\tB\n\xbaH\x07r\x05\x10\x01\x18\x96\x01\"}\n\x19\x46inishRegistrationRequest\x12\x14\n\x02id\x18\x01 \x01(\tB\x08\xbaH\x05r\x03\xb0\x01\x01\x12J\n\x07payload\x18\x02 \x01(\x0b\x32\x31.registration.v1.FinishRegistrationRequestPayloadB\x06\xbaH\x03\xc8\x01\x01\"F\n\x1a\x46inishRegistrationResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07text_id\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\"&\n\x18\x43heckRegistrationRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1b\n\x19\x43heckRegistrationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'public.registration.v1.dto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FINISHREGISTRATIONREQUESTPAYLOAD'].fields_by_name['tenant_text_id']._loaded_options = None
  _globals['_FINISHREGISTRATIONREQUESTPAYLOAD'].fields_by_name['tenant_text_id']._serialized_options = b'\272H\007r\005\020\001\030\226\001'
  _globals['_FINISHREGISTRATIONREQUESTPAYLOAD'].fields_by_name['profile_name']._loaded_options = None
  _globals['_FINISHREGISTRATIONREQUESTPAYLOAD'].fields_by_name['profile_name']._serialized_options = b'\272H\007r\005\020\001\030\226\001'
  _globals['_FINISHREGISTRATIONREQUESTPAYLOAD'].fields_by_name['profile_surname']._loaded_options = None
  _globals['_FINISHREGISTRATIONREQUESTPAYLOAD'].fields_by_name['profile_surname']._serialized_options = b'\272H\007r\005\020\001\030\226\001'
  _globals['_FINISHREGISTRATIONREQUEST'].fields_by_name['id']._loaded_options = None
  _globals['_FINISHREGISTRATIONREQUEST'].fields_by_name['id']._serialized_options = b'\272H\005r\003\260\001\001'
  _globals['_FINISHREGISTRATIONREQUEST'].fields_by_name['payload']._loaded_options = None
  _globals['_FINISHREGISTRATIONREQUEST'].fields_by_name['payload']._serialized_options = b'\272H\003\310\001\001'
  _globals['_STARTREGISTRATIONREQUEST']._serialized_start=141
  _globals['_STARTREGISTRATIONREQUEST']._serialized_end=182
  _globals['_STARTREGISTRATIONRESPONSE']._serialized_start=184
  _globals['_STARTREGISTRATIONRESPONSE']._serialized_end=211
  _globals['_FINISHREGISTRATIONREQUESTPAYLOAD']._serialized_start=214
  _globals['_FINISHREGISTRATIONREQUESTPAYLOAD']._serialized_end=355
  _globals['_FINISHREGISTRATIONREQUEST']._serialized_start=357
  _globals['_FINISHREGISTRATIONREQUEST']._serialized_end=482
  _globals['_FINISHREGISTRATIONRESPONSE']._serialized_start=484
  _globals['_FINISHREGISTRATIONRESPONSE']._serialized_end=554
  _globals['_CHECKREGISTRATIONREQUEST']._serialized_start=556
  _globals['_CHECKREGISTRATIONREQUEST']._serialized_end=594
  _globals['_CHECKREGISTRATIONRESPONSE']._serialized_start=596
  _globals['_CHECKREGISTRATIONRESPONSE']._serialized_end=623
# @@protoc_insertion_point(module_scope)
