# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: public/registration/v1/service.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'public/registration/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from public.registration.v1 import dto_pb2 as public_dot_registration_dot_v1_dot_dto__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$public/registration/v1/service.proto\x12\x0fregistration.v1\x1a public/registration/v1/dto.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xcb\x03\n\x19RegistrationPublicService\x12\x8d\x01\n\x11StartRegistration\x12).registration.v1.StartRegistrationRequest\x1a*.registration.v1.StartRegistrationResponse\"!\x82\xd3\xe4\x93\x02\x1b\"\x16/v1/registration/start:\x01*\x12\x91\x01\n\x12\x46inishRegistration\x12*.registration.v1.FinishRegistrationRequest\x1a+.registration.v1.FinishRegistrationResponse\"\"\x82\xd3\xe4\x93\x02\x1c\"\x17/v1/registration/finish:\x01*\x12\x89\x01\n\x11\x43heckRegistration\x12).registration.v1.CheckRegistrationRequest\x1a*.registration.v1.CheckRegistrationResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/registration/{id}b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'public.registration.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTRATIONPUBLICSERVICE'].methods_by_name['StartRegistration']._loaded_options = None
  _globals['_REGISTRATIONPUBLICSERVICE'].methods_by_name['StartRegistration']._serialized_options = b'\202\323\344\223\002\033\"\026/v1/registration/start:\001*'
  _globals['_REGISTRATIONPUBLICSERVICE'].methods_by_name['FinishRegistration']._loaded_options = None
  _globals['_REGISTRATIONPUBLICSERVICE'].methods_by_name['FinishRegistration']._serialized_options = b'\202\323\344\223\002\034\"\027/v1/registration/finish:\001*'
  _globals['_REGISTRATIONPUBLICSERVICE'].methods_by_name['CheckRegistration']._loaded_options = None
  _globals['_REGISTRATIONPUBLICSERVICE'].methods_by_name['CheckRegistration']._serialized_options = b'\202\323\344\223\002\027\022\025/v1/registration/{id}'
  _globals['_REGISTRATIONPUBLICSERVICE']._serialized_start=170
  _globals['_REGISTRATIONPUBLICSERVICE']._serialized_end=629
# @@protoc_insertion_point(module_scope)
