# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: public/users_tenant/v1/service.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'public/users_tenant/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from public.users_tenant.v1 import dto_pb2 as public_dot_users__tenant_dot_v1_dot_dto__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$public/users_tenant/v1/service.proto\x12\x0fusers_tenant.v1\x1a public/users_tenant/v1/dto.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xf8\x08\n\x18UsersTenantPublicService\x12\x8a\x01\n\x0cListAccounts\x12$.users_tenant.v1.ListAccountsRequest\x1a%.users_tenant.v1.ListAccountsResponse\"-\x92\x41\x12\x62\x10\n\x0e\n\nBearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/tenant/users\x12\x89\x01\n\nGetAccount\x12\".users_tenant.v1.GetAccountRequest\x1a#.users_tenant.v1.GetAccountResponse\"2\x92\x41\x12\x62\x10\n\x0e\n\nBearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/tenant/users/{id}\x12\x90\x01\n\rCreateAccount\x12%.users_tenant.v1.CreateAccountRequest\x1a&.users_tenant.v1.CreateAccountResponse\"0\x92\x41\x12\x62\x10\n\x0e\n\nBearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x15\"\x10/v1/tenant/users:\x01*\x12\x92\x01\n\x0cPatchAccount\x12$.users_tenant.v1.PatchAccountRequest\x1a%.users_tenant.v1.PatchAccountResponse\"5\x92\x41\x12\x62\x10\n\x0e\n\nBearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1a\x32\x15/v1/tenant/users/{id}:\x01*\x12\xa1\x01\n\x0fUpdateMyProfile\x12\'.users_tenant.v1.UpdateMyProfileRequest\x1a(.users_tenant.v1.UpdateMyProfileResponse\";\x92\x41\x12\x62\x10\n\x0e\n\nBearerAuth\x12\x00\x82\xd3\xe4\x93\x02 \x1a\x1b/v1/tenant/users/my-profile:\x01*\x12\xa5\x01\n\x10UpdateMyPassword\x12(.users_tenant.v1.UpdateMyPasswordRequest\x1a).users_tenant.v1.UpdateMyPasswordResponse\"<\x92\x41\x12\x62\x10\n\x0e\n\nBearerAuth\x12\x00\x82\xd3\xe4\x93\x02!\x1a\x1c/v1/tenant/users/my-password:\x01*\x12\xce\x01\n\x16UploadProfilePhotoFile\x12..users_tenant.v1.UploadProfilePhotoFileRequest\x1a/.users_tenant.v1.UploadProfilePhotoFileResponse\"S\x92\x41\'2\x13multipart/form-datab\x10\n\x0e\n\nBearerAuth\x12\x00\x82\xd3\xe4\x93\x02#\"\x1e/v1/tenant/users/profile-photo:\x01*b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'public.users_tenant.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERSTENANTPUBLICSERVICE'].methods_by_name['ListAccounts']._loaded_options = None
  _globals['_USERSTENANTPUBLICSERVICE'].methods_by_name['ListAccounts']._serialized_options = b'\222A\022b\020\n\016\n\nBearerAuth\022\000\202\323\344\223\002\022\022\020/v1/tenant/users'
  _globals['_USERSTENANTPUBLICSERVICE'].methods_by_name['GetAccount']._loaded_options = None
  _globals['_USERSTENANTPUBLICSERVICE'].methods_by_name['GetAccount']._serialized_options = b'\222A\022b\020\n\016\n\nBearerAuth\022\000\202\323\344\223\002\027\022\025/v1/tenant/users/{id}'
  _globals['_USERSTENANTPUBLICSERVICE'].methods_by_name['CreateAccount']._loaded_options = None
  _globals['_USERSTENANTPUBLICSERVICE'].methods_by_name['CreateAccount']._serialized_options = b'\222A\022b\020\n\016\n\nBearerAuth\022\000\202\323\344\223\002\025\"\020/v1/tenant/users:\001*'
  _globals['_USERSTENANTPUBLICSERVICE'].methods_by_name['PatchAccount']._loaded_options = None
  _globals['_USERSTENANTPUBLICSERVICE'].methods_by_name['PatchAccount']._serialized_options = b'\222A\022b\020\n\016\n\nBearerAuth\022\000\202\323\344\223\002\0322\025/v1/tenant/users/{id}:\001*'
  _globals['_USERSTENANTPUBLICSERVICE'].methods_by_name['UpdateMyProfile']._loaded_options = None
  _globals['_USERSTENANTPUBLICSERVICE'].methods_by_name['UpdateMyProfile']._serialized_options = b'\222A\022b\020\n\016\n\nBearerAuth\022\000\202\323\344\223\002 \032\033/v1/tenant/users/my-profile:\001*'
  _globals['_USERSTENANTPUBLICSERVICE'].methods_by_name['UpdateMyPassword']._loaded_options = None
  _globals['_USERSTENANTPUBLICSERVICE'].methods_by_name['UpdateMyPassword']._serialized_options = b'\222A\022b\020\n\016\n\nBearerAuth\022\000\202\323\344\223\002!\032\034/v1/tenant/users/my-password:\001*'
  _globals['_USERSTENANTPUBLICSERVICE'].methods_by_name['UploadProfilePhotoFile']._loaded_options = None
  _globals['_USERSTENANTPUBLICSERVICE'].methods_by_name['UploadProfilePhotoFile']._serialized_options = b'\222A\'2\023multipart/form-datab\020\n\016\n\nBearerAuth\022\000\202\323\344\223\002#\"\036/v1/tenant/users/profile-photo:\001*'
  _globals['_USERSTENANTPUBLICSERVICE']._serialized_start=170
  _globals['_USERSTENANTPUBLICSERVICE']._serialized_end=1314
# @@protoc_insertion_point(module_scope)
