# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from public.users_tenant.v1 import dto_pb2 as public_dot_users__tenant_dot_v1_dot_dto__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in public/users_tenant/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsersTenantPublicServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAccounts = channel.unary_unary(
                '/users_tenant.v1.UsersTenantPublicService/ListAccounts',
                request_serializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.ListAccountsRequest.SerializeToString,
                response_deserializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.ListAccountsResponse.FromString,
                _registered_method=True)
        self.GetAccount = channel.unary_unary(
                '/users_tenant.v1.UsersTenantPublicService/GetAccount',
                request_serializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.GetAccountRequest.SerializeToString,
                response_deserializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.GetAccountResponse.FromString,
                _registered_method=True)
        self.CreateAccount = channel.unary_unary(
                '/users_tenant.v1.UsersTenantPublicService/CreateAccount',
                request_serializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.CreateAccountResponse.FromString,
                _registered_method=True)
        self.PatchAccount = channel.unary_unary(
                '/users_tenant.v1.UsersTenantPublicService/PatchAccount',
                request_serializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.PatchAccountRequest.SerializeToString,
                response_deserializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.PatchAccountResponse.FromString,
                _registered_method=True)
        self.UpdateMyProfile = channel.unary_unary(
                '/users_tenant.v1.UsersTenantPublicService/UpdateMyProfile',
                request_serializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.UpdateMyProfileRequest.SerializeToString,
                response_deserializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.UpdateMyProfileResponse.FromString,
                _registered_method=True)
        self.UpdateMyPassword = channel.unary_unary(
                '/users_tenant.v1.UsersTenantPublicService/UpdateMyPassword',
                request_serializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.UpdateMyPasswordRequest.SerializeToString,
                response_deserializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.UpdateMyPasswordResponse.FromString,
                _registered_method=True)
        self.UploadProfilePhotoFile = channel.unary_unary(
                '/users_tenant.v1.UsersTenantPublicService/UploadProfilePhotoFile',
                request_serializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.UploadProfilePhotoFileRequest.SerializeToString,
                response_deserializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.UploadProfilePhotoFileResponse.FromString,
                _registered_method=True)


class UsersTenantPublicServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListAccounts(self, request, context):
        """Список аккаунтов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccount(self, request, context):
        """Получить аккаунт
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Создать аккаунт
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PatchAccount(self, request, context):
        """Обновить аккаунт
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMyProfile(self, request, context):
        """Обновить мой профиль
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMyPassword(self, request, context):
        """Обновить мой пароль
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadProfilePhotoFile(self, request, context):
        """Загрузить фотографию профиля
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsersTenantPublicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccounts,
                    request_deserializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.ListAccountsRequest.FromString,
                    response_serializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.ListAccountsResponse.SerializeToString,
            ),
            'GetAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccount,
                    request_deserializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.GetAccountRequest.FromString,
                    response_serializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.GetAccountResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.CreateAccountRequest.FromString,
                    response_serializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.CreateAccountResponse.SerializeToString,
            ),
            'PatchAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.PatchAccount,
                    request_deserializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.PatchAccountRequest.FromString,
                    response_serializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.PatchAccountResponse.SerializeToString,
            ),
            'UpdateMyProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMyProfile,
                    request_deserializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.UpdateMyProfileRequest.FromString,
                    response_serializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.UpdateMyProfileResponse.SerializeToString,
            ),
            'UpdateMyPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMyPassword,
                    request_deserializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.UpdateMyPasswordRequest.FromString,
                    response_serializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.UpdateMyPasswordResponse.SerializeToString,
            ),
            'UploadProfilePhotoFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadProfilePhotoFile,
                    request_deserializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.UploadProfilePhotoFileRequest.FromString,
                    response_serializer=public_dot_users__tenant_dot_v1_dot_dto__pb2.UploadProfilePhotoFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'users_tenant.v1.UsersTenantPublicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('users_tenant.v1.UsersTenantPublicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsersTenantPublicService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users_tenant.v1.UsersTenantPublicService/ListAccounts',
            public_dot_users__tenant_dot_v1_dot_dto__pb2.ListAccountsRequest.SerializeToString,
            public_dot_users__tenant_dot_v1_dot_dto__pb2.ListAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users_tenant.v1.UsersTenantPublicService/GetAccount',
            public_dot_users__tenant_dot_v1_dot_dto__pb2.GetAccountRequest.SerializeToString,
            public_dot_users__tenant_dot_v1_dot_dto__pb2.GetAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users_tenant.v1.UsersTenantPublicService/CreateAccount',
            public_dot_users__tenant_dot_v1_dot_dto__pb2.CreateAccountRequest.SerializeToString,
            public_dot_users__tenant_dot_v1_dot_dto__pb2.CreateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PatchAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users_tenant.v1.UsersTenantPublicService/PatchAccount',
            public_dot_users__tenant_dot_v1_dot_dto__pb2.PatchAccountRequest.SerializeToString,
            public_dot_users__tenant_dot_v1_dot_dto__pb2.PatchAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMyProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users_tenant.v1.UsersTenantPublicService/UpdateMyProfile',
            public_dot_users__tenant_dot_v1_dot_dto__pb2.UpdateMyProfileRequest.SerializeToString,
            public_dot_users__tenant_dot_v1_dot_dto__pb2.UpdateMyProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMyPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users_tenant.v1.UsersTenantPublicService/UpdateMyPassword',
            public_dot_users__tenant_dot_v1_dot_dto__pb2.UpdateMyPasswordRequest.SerializeToString,
            public_dot_users__tenant_dot_v1_dot_dto__pb2.UpdateMyPasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadProfilePhotoFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users_tenant.v1.UsersTenantPublicService/UploadProfilePhotoFile',
            public_dot_users__tenant_dot_v1_dot_dto__pb2.UploadProfilePhotoFileRequest.SerializeToString,
            public_dot_users__tenant_dot_v1_dot_dto__pb2.UploadProfilePhotoFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
