# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: public/tenant/v1/dto.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'public/tenant/v1/dto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.types import types_pb2 as common_dot_types_dot_types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1apublic/tenant/v1/dto.proto\x12\ttenant.v1\x1a\x18\x63ommon/types/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1b\x62uf/validate/validate.proto\"\"\n\x0fIsExistsRequest\x12\x0f\n\x07text_id\x18\x01 \x01(\t\"\x12\n\x10IsExistsResponse\"C\n\x19PatchTenantRequestPayload\x12\x1d\n\x04name\x18\x01 \x01(\tB\n\xbaH\x07r\x05\x10\x01\x18\x96\x01H\x00\x88\x01\x01\x42\x07\n\x05_name\"\x96\x01\n\x12PatchTenantRequest\x12\x14\n\x02id\x18\x01 \x01(\tB\x08\xbaH\x05r\x03\xb0\x01\x01\x12=\n\x07payload\x18\x02 \x01(\x0b\x32$.tenant.v1.PatchTenantRequestPayloadB\x06\xbaH\x03\xc8\x01\x01\x12\x0f\n\x07version\x18\x03 \x01(\x03\x12\x1a\n\x12skip_version_check\x18\x04 \x01(\x08\"\x15\n\x13PatchTenantResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'public.tenant.v1.dto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PATCHTENANTREQUESTPAYLOAD'].fields_by_name['name']._loaded_options = None
  _globals['_PATCHTENANTREQUESTPAYLOAD'].fields_by_name['name']._serialized_options = b'\272H\007r\005\020\001\030\226\001'
  _globals['_PATCHTENANTREQUEST'].fields_by_name['id']._loaded_options = None
  _globals['_PATCHTENANTREQUEST'].fields_by_name['id']._serialized_options = b'\272H\005r\003\260\001\001'
  _globals['_PATCHTENANTREQUEST'].fields_by_name['payload']._loaded_options = None
  _globals['_PATCHTENANTREQUEST'].fields_by_name['payload']._serialized_options = b'\272H\003\310\001\001'
  _globals['_ISEXISTSREQUEST']._serialized_start=129
  _globals['_ISEXISTSREQUEST']._serialized_end=163
  _globals['_ISEXISTSRESPONSE']._serialized_start=165
  _globals['_ISEXISTSRESPONSE']._serialized_end=183
  _globals['_PATCHTENANTREQUESTPAYLOAD']._serialized_start=185
  _globals['_PATCHTENANTREQUESTPAYLOAD']._serialized_end=252
  _globals['_PATCHTENANTREQUEST']._serialized_start=255
  _globals['_PATCHTENANTREQUEST']._serialized_end=405
  _globals['_PATCHTENANTRESPONSE']._serialized_start=407
  _globals['_PATCHTENANTRESPONSE']._serialized_end=428
# @@protoc_insertion_point(module_scope)
