# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: public/tenant/v1/service.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'public/tenant/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from public.tenant.v1 import dto_pb2 as public_dot_tenant_dot_v1_dot_dto__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1epublic/tenant/v1/service.proto\x12\ttenant.v1\x1a\x1apublic/tenant/v1/dto.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\x81\x02\n\x13TenantPublicService\x12k\n\x08IsExists\x12\x1a.tenant.v1.IsExistsRequest\x1a\x1b.tenant.v1.IsExistsResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/tenant/is-exists/{text_id}\x12}\n\x0bPatchTenant\x12\x1d.tenant.v1.PatchTenantRequest\x1a\x1e.tenant.v1.PatchTenantResponse\"/\x92\x41\x12\x62\x10\n\x0e\n\nBearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x14\x32\x0f/v1/tenant/{id}:\x01*b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'public.tenant.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENANTPUBLICSERVICE'].methods_by_name['IsExists']._loaded_options = None
  _globals['_TENANTPUBLICSERVICE'].methods_by_name['IsExists']._serialized_options = b'\202\323\344\223\002 \022\036/v1/tenant/is-exists/{text_id}'
  _globals['_TENANTPUBLICSERVICE'].methods_by_name['PatchTenant']._loaded_options = None
  _globals['_TENANTPUBLICSERVICE'].methods_by_name['PatchTenant']._serialized_options = b'\222A\022b\020\n\016\n\nBearerAuth\022\000\202\323\344\223\002\0242\017/v1/tenant/{id}:\001*'
  _globals['_TENANTPUBLICSERVICE']._serialized_start=152
  _globals['_TENANTPUBLICSERVICE']._serialized_end=409
# @@protoc_insertion_point(module_scope)
