# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from public.tenant.v1 import dto_pb2 as public_dot_tenant_dot_v1_dot_dto__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in public/tenant/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TenantPublicServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IsExists = channel.unary_unary(
                '/tenant.v1.TenantPublicService/IsExists',
                request_serializer=public_dot_tenant_dot_v1_dot_dto__pb2.IsExistsRequest.SerializeToString,
                response_deserializer=public_dot_tenant_dot_v1_dot_dto__pb2.IsExistsResponse.FromString,
                _registered_method=True)
        self.PatchTenant = channel.unary_unary(
                '/tenant.v1.TenantPublicService/PatchTenant',
                request_serializer=public_dot_tenant_dot_v1_dot_dto__pb2.PatchTenantRequest.SerializeToString,
                response_deserializer=public_dot_tenant_dot_v1_dot_dto__pb2.PatchTenantResponse.FromString,
                _registered_method=True)


class TenantPublicServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IsExists(self, request, context):
        """Проверка на существование
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PatchTenant(self, request, context):
        """Обновление тенанта
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TenantPublicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IsExists': grpc.unary_unary_rpc_method_handler(
                    servicer.IsExists,
                    request_deserializer=public_dot_tenant_dot_v1_dot_dto__pb2.IsExistsRequest.FromString,
                    response_serializer=public_dot_tenant_dot_v1_dot_dto__pb2.IsExistsResponse.SerializeToString,
            ),
            'PatchTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.PatchTenant,
                    request_deserializer=public_dot_tenant_dot_v1_dot_dto__pb2.PatchTenantRequest.FromString,
                    response_serializer=public_dot_tenant_dot_v1_dot_dto__pb2.PatchTenantResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tenant.v1.TenantPublicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tenant.v1.TenantPublicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TenantPublicService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IsExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tenant.v1.TenantPublicService/IsExists',
            public_dot_tenant_dot_v1_dot_dto__pb2.IsExistsRequest.SerializeToString,
            public_dot_tenant_dot_v1_dot_dto__pb2.IsExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PatchTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tenant.v1.TenantPublicService/PatchTenant',
            public_dot_tenant_dot_v1_dot_dto__pb2.PatchTenantRequest.SerializeToString,
            public_dot_tenant_dot_v1_dot_dto__pb2.PatchTenantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
